version: "3.8"

services:
  db:
    container_name: db
    image: postgres:latest
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
    ports:
      - "5432:5432"
    networks:
      ketfilmstore:
    volumes:
      - pgsql-volume-data:/var/lib/postgresql/data
    restart: always
  restapi:
    container_name: restapi
    image: sukute1712/ket-film-store:latest
    env_file: .env
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      ketfilmstore:
    restart: on-failure

networks:
  ketfilmstore:

volumes:
  pgsql-volume-data: